# Generated by Django 5.0 on 2023-12-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invo_id', models.AutoField(primary_key=True, serialize=False)),
                ('invo_date', models.DateField()),
                ('user_id', models.IntegerField()),
                ('expedition_date', models.DateField()),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('ivo_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.IntegerField()),
                ('quantity_invo_det', models.IntegerField()),
                ('invo_price_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Invoice_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Pay_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_name', models.CharField(max_length=255)),
                ('prov_dni', models.CharField(max_length=20)),
                ('prov_phone', models.CharField(max_length=20)),
                ('prov_email', models.EmailField(max_length=254)),
                ('prov_city', models.CharField(max_length=100)),
                ('prov_status', models.CharField(max_length=50)),
                ('prov_type', models.CharField(max_length=50)),
                ('prov_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Providers',
                'managed': False,
            },
        ),
    ]
