# Generated by Django 5.0 on 2023-12-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_compras', '0004_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personales'},
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
