# Generated by Django 5.0 on 2024-01-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_compras', '0007_alter_invoice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
            ],
        ),
    ]
